### ISSUE TITLE
Add support for CanvasOverlays

### ISSUE THREAD

**Issue by gerald-curley** [inaiat/jqplot4java#29]
Hi,

I've produced a fork that adds support CanvasOverlays and BarSeriesCharts as well as fixing/adding some other things that were needed for a wicket project last year.
Would you be interested in considering these changes for a new release of jqplot4java?

Thanks,

Gerald.

**Comment by inaiat** [comment]
Yes!!! I am very busy with my new job!!! :D Thanks!

**Comment by gerald-curley** [comment]
Thanks.

I’ve submitted the pull request now.


G.






Sent from Windows Mail





From: Inaiat Henrique
Sent: ‎Tuesday‎, ‎26‎ ‎January‎ ‎2016 ‎20‎:‎35
To: inaiat/jqplot4java
Cc: Gerald Curley




Yes!!! I am very busy with my new job!!! :D Thanks!

**Comment by gerald-curley** [comment]
Thank you.

Please can you let me know when the next release will be available on maven?

**Comment by inaiat** [comment]
Hi Gerald,

on weekend.

Thanks!!

**Comment by inaiat** [comment]
Hi Gerard,

I lost my account from sonatype... I think that sonatype is in trouble to
send me email to reset my password.

**Comment by gerald-curley** [comment]
Ok, sorry to hear about that. Hopefully you can get the password reset.
Please let me know when the new release is available.

Thanks, 

Gerald.

----- Sent from mBox Mail Hotmail for iPhone and iPod Touch http://www.fluentfactory.com/mboxmail

________________________

**Comment by inaiat** [comment]
Hi Gerald,

Finally the deploy is done! :D Sorry for delay, but I had a lot of work on
my new job.

Thanks in advanced.

**Comment by gerald-curley** [comment]
Thanks for letting me know.


G.






Sent from Windows Mail





From: Inaiat Henrique
Sent: ‎Saturday‎, ‎2‎ ‎April‎ ‎2016 ‎23‎:‎26
To: inaiat/jqplot4java
Cc: Gerald Curley



Hi Gerald,

Finally the deploy is done! :D Sorry for delay, but I had a lot of work on
my new job.

Thanks in advanced.
