### ISSUE TITLE
Dependency to Json need to be removed

### ISSUE THREAD

**Issue by solomax** [inaiat/jqplot4java#34]
Hello,

Recently Json license was declared NOT to be fully compatible with APL v2 (discussion [1])
Can you please change following dependency org.json:json:20090211 with com.tdunning:json:1.1 ?

BTW version 1.3.2 of your library is not available in Maven central for some reason :((

[1] http://markmail.org/message/wblioyxpl2uocqpi

**Comment by solomax** [comment]
@inaiat ping :)

**Comment by inaiat** [comment]
Sorry!! :D I will change!

**Comment by inaiat** [comment]
Ji Solomax, 

I changed to com.tdunning, but units tests are broken. Can you help me?

Thanks.

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.007 sec <<< FAILURE! - in br.com.digilabs.jqplot.test.LineChartTest
testAddValues(br.com.digilabs.jqplot.test.LineChartTest)  Time elapsed: 0.005 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.json.JSONArray.put(Ljava/util/Collection;)Lorg/json/JSONArray;
        at br.com.digilabs.jqplot.data.LinedData.toJsonString(LinedData.java:81)
        at br.com.digilabs.jqplot.JqPlotUtils.createJquery(JqPlotUtils.java:88)
        at br.com.digilabs.jqplot.JqPlotUtils.createJquery(JqPlotUtils.java:71)
        at br.com.digilabs.jqplot.test.LineChartTest.testAddValues(LineChartTest.java:38)

**Comment by solomax** [comment]
@inaiat sure, but how can I run it?
Build is successfull in my fork, `mvn test` also successful:
```
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
what am I doing wrong?

**Comment by solomax** [comment]
Also success with java7 ....

**Comment by solomax** [comment]
Just have checked internals
JSONArray.put(Ljava/util/Collection;) of old library works differently than JSONArray.put(Ljava/lang/Object;)
Will contact library maintainer and will propose the patch

**Comment by solomax** [comment]
Done: https://github.com/tdunning/open-json/pull/4

**Comment by solomax** [comment]
I have updated Json library version in PR, now it includes necessary method

**Comment by inaiat** [comment]
Hi Solomax. PR applied and 1.3.3 released! Thanks in advanced! :D

**Comment by solomax** [comment]
Thanks!
